title: Zhada Eaves
logo: images/Growth Portfolio Headshot.png
description: Powered with a diverse background that will bring a new dynamic to any team, I am a data-driven product developer. Passionate about analyzing and researching problems, collecting data, and finding creative solutions.
#show_download: True
theme: jekyll-theme-minimal
