title: Zhada Eaves
logo: images/Growth Portfolio Headshot.png
description: With a diverse background that brings a fresh perspective, I’m a data-driven problem solver. I thrive on uncovering insights, connecting patterns, and using data to create impactful marketing, healthcare, or business solutions.
#show_download: True
theme: jekyll-theme-minimal
