title: Zhada Eaves, MS, BSN
logo: images/Growth Portfolio Headshot.png
description: Powered with a diverse background that will bring a new dynamic to any team, I am a data-driven product developer. I am passionate about analyzing and researching problems, collecting data, and finding creative solutions. How can we work together?
#show_download: True
theme: jekyll-theme-minimal
